openapi: 3.0.0
info:
  title: 認証 API
  version: 1.0.0

paths:
  /auth/login:
    post:
      operationId: authLogin
      summary: ログインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        401:
          description: ログイン失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/me:
    get:
      operationId: authMe
      summary: 認証してユーザー情報を取得
      responses:
        200:
          description: 認証成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        401:
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
        statusCode:
          type: number
